name: Discussion Help Bot
on:
  discussion:
    types:
      - created
jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run discuss bot
        run: python script.py
